apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trisla.name" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "trisla.labels" . | nindent 4 }}
data:
  network.interface: {{ .Values.network.interface | quote }}
  network.nodeIP: {{ .Values.network.nodeIP | quote }}
  network.gateway: {{ .Values.network.gateway | quote }}
  production.enabled: {{ .Values.production.enabled | quote }}
  production.simulationMode: {{ .Values.production.simulationMode | quote }}
  production.useRealServices: {{ .Values.production.useRealServices | quote }}
  production.executeRealActions: {{ .Values.production.executeRealActions | quote }}

