{{- if .Values.besu.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trisla.name" . }}-besu-genesis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "trisla.labels" . | nindent 4 }}
    app.kubernetes.io/component: besu
data:
  genesis.json: |
{{ .Values.besu.genesis | indent 4 }}
{{- end }}
