apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trisla.name" . }}-nasp-adapter
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "trisla.labels" (dict "Values" .Values "Release" .Release "Chart" .Chart "component" "nasp-adapter") | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "trisla.name" . }}-nasp-adapter
  labels:
    {{- include "trisla.labels" (dict "Values" .Values "Release" .Release "Chart" .Chart "component" "nasp-adapter") | nindent 4 }}
rules:
  # CRDs - NetworkSliceInstances, NetworkSliceSubnetInstances, TriSLAReservations (MDCE v2 ledger)
  - apiGroups:
      - trisla.io
    resources:
      - networksliceinstances
      - networksliceinstances/status
      - networkslicesubnetinstances
      - networkslicesubnetinstances/status
      - trislareservations
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  # Namespaces (cluster-scoped)
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
      - create
  # ResourceQuotas e LimitRanges
  - apiGroups:
      - ""
    resources:
      - resourcequotas
      - limitranges
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  # NetworkPolicies
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "trisla.name" . }}-nasp-adapter
  labels:
    {{- include "trisla.labels" (dict "Values" .Values "Release" .Release "Chart" .Chart "component" "nasp-adapter") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "trisla.name" . }}-nasp-adapter
subjects:
  - kind: ServiceAccount
    name: {{ include "trisla.name" . }}-nasp-adapter
    namespace: {{ .Values.global.namespace }}

