apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: {{ .Values.global.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

{{- define "imagePullSecret" }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.global.imageRegistry .Values.global.ghcrUser .Values.global.ghcrToken (printf "%s:%s" .Values.global.ghcrUser .Values.global.ghcrToken | b64enc) | b64enc }}
{{- end }}

