{{- if and  .Values.global.ghcrUser  .Values.global.ghcrToken }}
{{/*
GHCR Secret - Only created if ghcrUser and ghcrToken are provided via --set or external values file
This allows the chart to work without requiring these values, but enables secret creation when needed.
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "trisla.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "trisla.ghcrDockerConfig" . }}
{{- end }}

