apiVersion: v1
kind: Service
metadata:
  name: {{ include "trisla.name" . }}-sla-agent-layer
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "trisla.labels" (merge . (dict "component" "sla-agent-layer")) | nindent 4 }}
spec:
  type: {{ .Values.slaAgentLayer.service.type }}
  ports:
  - port: {{ .Values.slaAgentLayer.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "trisla.selectorLabels" (merge . (dict "component" "sla-agent-layer")) | nindent 4 }}

