apiVersion: v1
kind: Service
metadata:
  name: {{ include "trisla.name" . }}-nasp-adapter
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "trisla.labels" (dict "Values" .Values "Release" .Release "Chart" .Chart "component" "nasp-adapter") | nindent 4 }}
spec:
  type: {{ .Values.naspAdapter.service.type }}
  ports:
  - port: {{ .Values.naspAdapter.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: trisla-nasp-adapter
    app.kubernetes.io/name: {{ include "trisla.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}































