{{- if .Values.besu.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trisla.name" . }}-besu
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "trisla.labels" . | nindent 4 }}
    app: besu
    component: blockchain
spec:
  type: {{ .Values.besu.service.type }}
  ports:
  - port: {{ .Values.besu.service.port }}
    targetPort: 8545
    protocol: TCP
    name: rpc
  - port: {{ .Values.besu.service.wsPort | default 8546 }}
    targetPort: 8546
    protocol: TCP
    name: rpc-ws
  - port: {{ .Values.besu.service.p2pPort | default 30303 }}
    targetPort: 30303
    protocol: TCP
    name: p2p
  selector:
    {{- include "trisla.selectorLabels" . | nindent 4 }}
    app: besu
    component: blockchain
{{- end }}
