apiVersion: v1
kind: Service
metadata:
  name: {{ include "trisla.name" . }}-decision-engine
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "trisla.labels" (merge . (dict "component" "decision-engine")) | nindent 4 }}
spec:
  type: {{ .Values.decisionEngine.service.type }}
  ports:
  - port: {{ .Values.decisionEngine.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: trisla-decision-engine
    app.kubernetes.io/name: {{ include "trisla.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}


