apiVersion: v1
kind: Service
metadata:
  name: {{ include "trisla.name" . }}-nasp-adapter
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "trisla.labels" (merge . (dict "component" "nasp-adapter")) | nindent 4 }}
spec:
  type: {{ .Values.naspAdapter.service.type }}
  ports:
  - port: {{ .Values.naspAdapter.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "trisla.selectorLabels" (merge . (dict "component" "nasp-adapter")) | nindent 4 }}




