apiVersion: v2
name: trisla
description: TriSLA - SLA-Aware Architecture for 5G/O-RAN
type: application
version: 3.7.10
appVersion: "3.7.10"
keywords:
  - 5g
  - o-ran
  - sla
  - network-slicing
  - blockchain
  - besu
maintainers:
  - name: TriSLA Team
    email: abelisboa@gmail.com

dependencies:
  - name: trisla-besu
    version: 1.0.0
    repository: "file://../trisla-besu"
    condition: trisla-besu.enabled
