global:
  namespace: trisla
  imageRegistry: ghcr.io/abelisboa
  imagePullSecrets:
  - name: ghcr-secret
  nodeSelector:
    kubernetes.io/hostname: node1
  env:
    OTLP_ENABLED: false
    KAFKA_ENABLED: false
    BC_ENABLED: false
    NASP_MODE: production
  otlpEnabled: false
  kafkaEnabled: false
  bcEnabled: false
  naspMode: production
network:
  interface: my5g
  nodeIP: 192.168.10.16
  gateway: 192.168.10.1
bcNssmf:
  enabled: true
  image:
    repository: trisla-bc-nssmf
    tag: 3.7.10
    pullPolicy: IfNotPresent
  service:
    port: 8083
  replicaCount: 1
  nodeSelector:
    kubernetes.io/hostname: node1
decisionEngine:
  enabled: true
  image:
    repository: trisla-decision-engine
    tag: 3.7.10
    pullPolicy: IfNotPresent
  service:
    port: 8082
  replicaCount: 2  # Alta disponibilidade (HA)
  nodeSelector:
    kubernetes.io/hostname: node1
mlNsmf:
  enabled: true
  image:
    repository: trisla-ml-nsmf
    tag: 3.7.10
    pullPolicy: IfNotPresent
  service:
    port: 8081
  replicaCount: 1
  nodeSelector:
    kubernetes.io/hostname: node1
naspAdapter:
  enabled: true
  image:
    repository: trisla-nasp-adapter
    tag: 3.7.10
    pullPolicy: IfNotPresent
  service:
    port: 8085
  replicaCount: 1
  nodeSelector:
    kubernetes.io/hostname: node1
semCsmf:
  env:
    DECISION_ENGINE_URL: http://10.233.59.75:8082/api/v1/decide
  enabled: true
  image:
    repository: trisla-sem-csmf
    tag: 3.7.10
    pullPolicy: IfNotPresent
  service:
    port: 8080
  replicaCount: 1
  nodeSelector:
    kubernetes.io/hostname: node1
slaAgentLayer:
  enabled: true
  image:
    repository: trisla-sla-agent-layer
    tag: 3.7.10
    pullPolicy: IfNotPresent
  service:
    port: 8084
  replicaCount: 1
  nodeSelector:
    kubernetes.io/hostname: node1
uiDashboard:
  enabled: true
  image:
    repository: trisla-ui-dashboard
    tag: 3.7.10
    pullPolicy: IfNotPresent
  service:
    port: 80
  replicaCount: 1
  nodeSelector:
    kubernetes.io/hostname: node1
