global:
  imagePullPolicy: IfNotPresent
  version: "v3.7.29"
  imageRegistry: "ghcr.io/abelisboa"

portalFrontend:
  enabled: true
  image:
    repository: trisla-portal-frontend
    tag: "v3.7.29"

portalBackend:
  enabled: true
  image:
    repository: trisla-portal-backend
    tag: "v3.7.29"

semCsmf:
  enabled: true
  image:
    repository: trisla-sem-csmf
    tag: "v3.7.29"

mlNsmf:
  enabled: true
  image:
    repository: trisla-ml-nsmf
    tag: "v3.7.29"

decisionEngine:
  enabled: true
  image:
    repository: trisla-decision-engine
    tag: "v3.7.29"
  env:
    # garante Estratégia B
    SLA_AGENT_URL: "http://trisla-sla-agent-layer:8084"
    PORT: "8082"

slaAgentLayer:
  enabled: true
  image:
    repository: trisla-sla-agent-layer
    tag: "v3.7.29"
  env:
    NASP_ADAPTER_URL: "http://trisla-nasp-adapter:8085"
    BC_NSSMF_URL: "http://trisla-bc-nssmf:8090"

naspAdapter:
  enabled: true
  image:
    repository: trisla-nasp-adapter
    tag: "v3.7.29"
  env:
    # força modo CRD-first real (sem chamar endpoints TCP/telecom como se fossem HTTP)
    NASP_EXECUTION_MODE: "crd"
    NASP_PROXY_ENABLED: "false"

bcNssmf:
  enabled: true
  image:
    repository: trisla-bc-nssmf
    tag: "v3.7.29"
  env:
    TRISLA_RPC_URL: "http://trisla-besu:8545"

besu:
  enabled: true
  image:
    repository: trisla-besu
    tag: "v3.7.29"

uiDashboard:
  enabled: true
  image:
    repository: trisla-ui-dashboard
    tag: "v3.7.29"
