# ============================================
# Inventory Ansible YAML - TriSLA NASP
# ============================================
# Invent√°rio para deploy local 127.0.0.1
# ============================================

[nasp]
127.0.0.1 ansible_connection=local ansible_python_interpreter=/usr/bin/python3
