apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trisla.name" . }}-nasp-adapter
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "trisla.labels" (merge . (dict "component" "nasp-adapter")) | nindent 4 }}
spec:
  replicas: {{ .Values.naspAdapter.replicas }}
  selector:
    matchLabels:
      {{- include "trisla.selectorLabels" (merge . (dict "component" "nasp-adapter")) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trisla.selectorLabels" (merge . (dict "component" "nasp-adapter")) | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      containers:
      - name: nasp-adapter
        image: {{ include "trisla.image" (merge .Values.naspAdapter.image (dict "Values" .Values)) }}
        ports:
        - containerPort: {{ .Values.naspAdapter.service.port }}
          name: http
        env:
        - name: TRISLA_NODE_INTERFACE
          value: {{ .Values.network.interface | quote }}
        - name: TRISLA_NODE_IP
          value: {{ .Values.network.nodeIP | quote }}
        - name: OTLP_ENDPOINT
          value: "http://{{ include "trisla.name" . }}-otel-collector:4317"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          {{- toYaml .Values.naspAdapter.resources | nindent 10 }}


