apiVersion: v1
kind: Service
metadata:
  name: {{ include "trisla-portal.fullname" . }}-frontend
  labels:
    {{- include "trisla-portal.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "trisla-portal.selectorLabels" . | nindent 4 }}
    component: frontend







