apiVersion: v1
kind: Service
metadata:
  name: {{ include "trisla-portal.fullname" . }}-backend
  labels:
    {{- include "trisla-portal.labels" . | nindent 4 }}
    component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "trisla-portal.selectorLabels" . | nindent 4 }}
    component: backend







