apiVersion: v1
kind: Service
metadata:
  name: trisla-portal-backend
  namespace: {{ .Values.global.namespace | default "trisla" }}
  labels:
    app: trisla-portal-backend
    component: backend
spec:
  type: NodePort
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    protocol: TCP
    nodePort: {{ .Values.backend.nodePort }}
  selector:
    app: trisla-portal-backend

