apiVersion: v1
kind: Service
metadata:
  name: trisla-portal-frontend
  namespace: {{ .Values.global.namespace | default "trisla" }}
  labels:
    app: trisla-portal-frontend
    component: frontend
spec:
  type: NodePort
  ports:
  - name: http
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
    nodePort: {{ .Values.frontend.nodePort }}
  selector:
    app: trisla-portal-frontend
