apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trisla-besu.fullname" . }}-genesis
  labels:
    {{- include "trisla-besu.labels" . | nindent 4 }}
data:
  genesis.json: |
{{ .Files.Get "genesis.json" | indent 4 }}
