apiVersion: v1
kind: Service
metadata:
  name: {{ include "trisla-besu.fullname" . }}
  labels:
    {{- include "trisla-besu.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.wsPort }}
      targetPort: ws
      protocol: TCP
      name: ws
    - port: {{ .Values.service.p2pPort }}
      targetPort: p2p
      protocol: TCP
      name: p2p
  selector:
    {{- include "trisla-besu.selectorLabels" . | nindent 4 }}
