apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trisla.name" . }}-sla-agent-layer
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "trisla.labels" (dict "Values" .Values "Release" .Release "Chart" .Chart "component" "sla-agent-layer") | nindent 4 }}
spec:
  replicas: {{ .Values.slaAgentLayer.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: trisla-sla-agent-layer
      app.kubernetes.io/name: {{ include "trisla.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: trisla-sla-agent-layer
        app.kubernetes.io/name: {{ include "trisla.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      nodeSelector:
        kubernetes.io/hostname: node1
      containers:
      - name: sla-agent-layer
        image: {{ include "trisla.image" (dict "Values" .Values "image" .Values.slaAgentLayer.image) }}
        ports:
        - containerPort: {{ .Values.slaAgentLayer.service.port }}
          name: http
        env:
        - name: TRISLA_NODE_INTERFACE
          value: {{ .Values.network.interface | quote }}
        - name: TRISLA_NODE_IP
          value: {{ .Values.network.nodeIP | quote }}
        - name: OTLP_ENDPOINT
          value: "http://{{ include "trisla.name" . }}-otel-collector:4317"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          {{- toYaml .Values.slaAgentLayer.resources | nindent 10 }}
