{{- if .Values.uiDashboard.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "trisla.name" . }}-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "trisla.labels" (dict "Values" .Values "Release" .Release "Chart" .Chart "component" "ingress") | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.uiDashboard.ingress.className }}
  rules:
  {{- range .Values.uiDashboard.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      - path: {{ .path | default "/" }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "trisla.name" $ }}-ui-dashboard
            port:
              number: 80
  {{- end }}
{{- end }}
